version: '3.1'

services:
  web:
    build: .
    ports:
      - "0.0.0.0:5000:5000/tcp"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DataContext=Host=db;Port=5432;Database=flatrent;User Id=postgres;Password=cosytest;
      - Mailgun__APIKey=ddfbeb5e041d52abee2cc26d9483af2e-e566273b-355506ba
      - VIRTUAL_HOST=cosy.maslinskas.lt
      - LETSENCRYPT_HOST=cosy.maslinskas.lt
      - LETSENCRYPT_EMAIL=ignasmaslinskas@gmail.com
      - ASPNETCORE_URLS=http://+:5000
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: cosytest